
import { Case, Rarity, NFTItem, Language } from './types';

export const RARITY_VALUES: Record<Rarity, number> = {
  Common: 25,
  Rare: 75,
  Epic: 250,
  Legendary: 750,
};

export const CASES_DATA: Case[] = [
  { id: 'case-bitch', name: 'Bitch', price: 100, rarity: 'Common', image: 'https://iili.io/fMg77LB.png' },
  { id: 'case-cigar', name: 'Cigar', price: 225, rarity: 'Common', image: 'https://iili.io/fMg7GkJ.png' },
  { id: 'case-dep', name: 'Dep', price: 350, rarity: 'Common', image: 'https://iili.io/fMgYenV.png' },
  { id: 'case-infinity', name: 'Infinity', price: 850, rarity: 'Rare', image: 'https://iili.io/fMg7s49.png' },
  { id: 'case-major', name: 'Major', price: 1600, rarity: 'Rare', image: 'https://iili.io/fMg74Q2.png' },
  { id: 'case-course', name: 'Course', price: 2250, rarity: 'Epic', image: 'https://iili.io/fMgaViN.png' },
  { id: 'case-zhdun', name: 'Zhdun', price: 3450, rarity: 'Epic', image: 'https://iili.io/fMgaxNj.png' },
  { id: 'case-dubai', name: 'Dubai', price: 4700, rarity: 'Legendary', image: 'https://iili.io/fMgazDx.png' },
];

export const FREE_CASES = [
  { id: 'free-promo', name: 'Бесплатный за промокод', price: 0, rarity: 'Common', type: 'promo', image: 'https://iili.io/fMg77LB.png' },
  { id: 'free-500', name: 'Бесплатный за пополнение 500+', price: 0, rarity: 'Rare', type: 'topup', min: 500, image: 'https://iili.io/fMg7s49.png' },
  { id: 'free-1000', name: 'Бесплатный за пополнение 1000+', price: 0, rarity: 'Rare', type: 'topup', min: 1000, image: 'https://iili.io/fMg74Q2.png' },
  { id: 'free-2500', name: 'Бесплатный за пополнение 2500+', price: 0, rarity: 'Epic', type: 'topup', min: 2500, image: 'https://iili.io/fMgaViN.png' },
  { id: 'free-5000', name: 'Бесплатный за пополнение 5000+', price: 0, rarity: 'Legendary', type: 'topup', min: 5000, image: 'https://iili.io/fMgazDx.png' },
];

export const PROMO_CODES = [
  { code: 'FREE', reward: 0 },
  { code: 'WELCOME', reward: 50 },
  { code: 'TON2024', reward: 100 },
];

const getRarityByValue = (val: number): Rarity => {
  if (val >= 10000) return 'Legendary';
  if (val >= 2500) return 'Epic';
  if (val >= 500) return 'Rare';
  return 'Common';
};

const RAW_MAPPING = [
  { n: "Artisan Brick", v: 61, i: "fMgcqsp" },
  { n: "Astral Shard", v: 137, i: "fMgcfXR" },
  { n: "B-day Candle", v: 2.5, i: "fMgcKzv" },
  { n: "Berry Box", v: 5.5, i: "fMgc3mJ" },
  { n: "Big Year", v: 3, i: "fMgc2ea" },
  { n: "Bling Binky", v: 24, i: "fMgcd5g" },
  { n: "Bonded Ring", v: 43, i: "fMgcJdF" },
  { n: "Bow Tie", v: 3.6, i: "fMgc9g1" },
  { n: "Bunny Muffin", v: 4.73, i: "fMgay0P" },
  { n: "Candy Cane", v: 3.18, i: "fMgabsV" },
  { n: "Clover Pin", v: 2.88, i: "fMgapqB" },
  { n: "Cookie Heart", v: 3.79, i: "fMgatzx" },
  { n: "Crystal Ball", v: 9.15, i: "fMgaDWQ" },
  { n: "Cupid Charm", v: 15.51, i: "fMgaQbj" },
  { n: "Desk Calendar", v: 2.41, i: "fMgaLOb" },
  { n: "Diamond Ring", v: 21.79, i: "fMgas5u" },
  { n: "Durov's Cap", v: 650, i: "fMgaiJe" },
  { n: "Easter Egg", v: 3.3, i: "fMga6g9" },
  { n: "Electric Skull", v: 26, i: "fMga407" },
  { n: "Eternal Candle", v: 4.7, i: "fMgaUs2" },
  { n: "Eternal Rose", v: 19.5, i: "fMgaSWl" },
  { n: "Evil Eye", v: 5.8, i: "fMga8x4" },
  { n: "Faith Amulet", v: 2.85, i: "fMgakbf" },
  { n: "Flying Broom", v: 8.86, i: "fMgaNJn" },
  { n: "Fresh Socks", v: 2.85, i: "fMgajUX" },
  { n: "Gem Signet", v: 54.97, i: "fMgaXfI" },
  { n: "Genie Lamp", v: 39.9, i: "fMgaViN" },
  { n: "Ginger Cookie", v: 3.88, i: "fMgaMVp" },
  { n: "Hanging Star", v: 5.91, i: "fMga0OJ" },
  { n: "Happy Brownie", v: 2.6, i: "fMgalRa" },
  { n: "Heart Locket", v: 1400.19, i: "fMga1Dv" },
  { n: "Heroic Helmet", v: 200, i: "fMgacHg" },
  { n: "Hex Pot", v: 3.57, i: "fMga7l1" },
  { n: "Holiday Drink", v: 3.6, i: "fMgaAiB" },
  { n: "Homemade Cake", v: 2.79, i: "fMgauVV" },
  { n: "Hypno Lollipop", v: 2.9, i: "fMgaToQ" },
  { n: "Ice Cream", v: 2.35, i: "fMgazDx" },
  { n: "Input Key", v: 4.15, i: "fMgaxNj" },
  { n: "Instant Ramen", v: 2.35, i: "fMgaoAb" },
  { n: "Ion Gem", v: 69.49, i: "fMgaBSe" },
  { n: "Ionic Dryer", v: 13.58, i: "fMgafK7" },
  { n: "Jack in the Box", v: 3.75, i: "fMgaql9" },
  { n: "Jelly Bunny", v: 5.3, i: "fMgaFPS" },
  { n: "Jester Hat", v: 2.74, i: "fMgaHNf" },
  { n: "Jingle Bells", v: 4.18, i: "fMga9AG" },
  { n: "Jolly Chimp", v: 5.45, i: "fMgYy9s" },
  { n: "Joyful Bundle", v: 4.37, i: "fMgYmSn" },
  { n: "Khabib's Papakha", v: 22.27, i: "fMgYDFt" },
  { n: "Kissed Frog", v: 33.48, i: "fMgYZPI" },
  { n: "Light Sword", v: 4.35, i: "fMgYQMN" },
  { n: "Lol Pop", v: 2.37, i: "fMgYLnp" },
  { n: "Loot Bag", v: 89.8, i: "fMgY6AJ" },
  { n: "Love Candle", v: 8.86, i: "fMgY49a" },
  { n: "Love Potion", v: 11.19, i: "fMgYg8g" },
  { n: "Low Rider", v: 32, i: "fMgYSF1" },
  { n: "Lunar Snake", v: 2.55, i: "fMgYv6P" },
  { n: "Lush Bouquet", v: 3.54, i: "fMgYkMB" },
  { n: "Mad Pumpkin", v: 12.25, i: "fMgYenV" },
  { n: "Magic Potion", v: 62.94, i: "fMgYNZQ" },
  { n: "Mighty Arm", v: 147, i: "fMgYjuj" },
  { n: "Mini Oscar", v: 73.39, i: "fMgYXyb" },
  { n: "Money Pot", v: 2.88, i: "fMgYwwx" },
  { n: "Moon Pendant", v: 2.99, i: "fMgYVae" },
  { n: "Mousse Cake", v: 2.7, i: "fMgYMF9" },
  { n: "Nail Bracelet", v: 94.82, i: "fMgY0n2" },
  { n: "Neko Helmet", v: 28.86, i: "fMgYcZl" },
  { n: "Party Sparkler", v: 3.57, i: "fMgYaj4" },
  { n: "Perfume Bottle", v: 69, i: "fMgYYuf" },
  { n: "Pet Snake", v: 2.93, i: "fMgY5yG" },
  { n: "Plush Pepe", v: 5790, i: "fMgYRvs" },
  { n: "Precious Peach", v: 315, i: "fMgYu3X" },
  { n: "Pretty Posy", v: 2.94, i: "fMgYI4t" },
  { n: "Record Player", v: 11.97, i: "fMgYzGI" },
  { n: "Restless Jar", v: 3.69, i: "fMgYnQp" },
  { n: "Sakura Flower", v: 6.33, i: "fMgYBTv" },
  { n: "Santa Hat", v: 4.86, i: "fMgYfyJ" },
  { n: "Scared Cat", v: 64.44, i: "fMgYKva" },
  { n: "Sharp Tongue", v: 36.35, i: "fMgYFYg" },
  { n: "Signet Ring", v: 28, i: "fMgY33F" },
  { n: "Skull Flower", v: 9.26, i: "fMgYd41" },
  { n: "Sky Stilettos", v: 9, i: "fMgYJEP" },
  { n: "Sleigh Bell", v: 7.8, i: "fMg7yQV" },
  { n: "Snake Box", v: 2.79, i: "fMg7phQ" },
  { n: "Snoop Cigar", v: 9.47, i: "fMg7mTx" },
  { n: "Snoop Dogg", v: 3.59, i: "fMg7Dpj" },
  { n: "Snow Globe", v: 5, i: "fMg7tkb" },
  { n: "Snow Mittens", v: 4.48, i: "fMg7Q2e" },
  { n: "Spiced Wine", v: 3.31, i: "fMg7s49" },
  { n: "Spring Basket", v: 3.74, i: "fMg7iE7" },
  { n: "Spy Agaric", v: 4.2, i: "fMg7PBS" },
  { n: "Star Notepad", v: 3.79, i: "fMg74Q2" },
  { n: "Stellar Rocket", v: 3.26, i: "fMg7rhl" },
  { n: "Swag Bag", v: 3.51, i: "fMg7gI4" },
  { n: "Swiss Watch", v: 37.82, i: "fMg78kG" },
  { n: "Tama Gadget", v: 3.2, i: "fMg7v7s" },
  { n: "Top Hat", v: 9.14, i: "fMg7OrX" },
  { n: "Toy Bear", v: 30.62, i: "fMg7N1t" },
  { n: "Trapped Heart", v: 9.8, i: "fMg7wBI" },
  { n: "UFC Strike", v: 18, i: "fMg7XXp" },
  { n: "Valentine Box", v: 7.3, i: "fMg7Mmv" },
  { n: "Vintage Cigar", v: 25.8, i: "fMg7GkJ" },
  { n: "Voodoo Doll", v: 23.69, i: "fMg7E7a" },
  { n: "Westside Sign", v: 62.5, i: "fMg71dg" },
  { n: "Whip Cupcake", v: 2.65, i: "fMg7lrF" },
  { n: "Winter Wreath", v: 3.59, i: "fMg7c11" },
  { n: "Witch Hat", v: 4.15, i: "fMg7aqP" },
  { n: "Xmas Stocking", v: 2.92, i: "fMg77LB" }
];

export const NFT_POOL: NFTItem[] = RAW_MAPPING.map((item, idx) => {
  const stars = Math.floor(item.v * 100);
  return {
    id: `pool-${idx}-${item.n.replace(/\s+/g, '-')}`,
    name: item.n,
    rarity: getRarityByValue(stars),
    image: `https://iili.io/${item.i}.png`,
    timestamp: Date.now(),
    value: stars
  };
});

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    app_name: 'GetGifts',
    free_cases: 'Free Cases',
    nft_cases: 'Cases with NFT',
    available_cases: 'Cases',
    open: 'Open Case',
    stars: 'STARS',
    stars_balance: 'Balance',
    nft_items: 'NFT Items',
    my_inventory: 'Inventory',
    promo_code: 'Promo',
    upgrade: 'Upgrade',
    craft: 'Craft',
    cases: 'Cases',
    pvp: 'PvP',
    profile: 'Profile',
    sell: 'Sell',
    sell_all: 'Sell All',
    sell_all_confirm: 'Sell all items for',
    withdraw: 'Withdraw',
    upgrade_btn: 'Upgrade',
    select_nft: 'Choose NFT',
    select_target: 'Choose Prize',
    win_chance: 'Win Chance',
    result_win: 'Success!',
    result_loss: 'Fail...',
    recharge: 'Top Up',
    activate: 'Activate',
    cancel: 'Cancel',
    connect_wallet: 'Connect Wallet',
    processing: 'Processing...',
    possible_drops: 'Possible Drops',
    enter: 'Enter',
    promo_err: 'Invalid code'
  },
  ru: {
    app_name: 'GetGifts',
    free_cases: 'Бесплатные кейсы',
    nft_cases: 'Кейсы с NFT',
    available_cases: 'Кейсы',
    open: 'Открыть кейс',
    stars: 'STARS',
    stars_balance: 'Баланс',
    nft_items: 'NFT Подарки',
    my_inventory: 'Инвентарь',
    promo_code: 'Промокод',
    upgrade: 'Апгрейд',
    craft: 'Крафт',
    cases: 'Кейсы',
    pvp: 'PvP',
    profile: 'Профиль',
    sell: 'Продать',
    sell_all: 'Продать всё',
    sell_all_confirm: 'Продать все предметы за',
    withdraw: 'Вывести',
    upgrade_btn: 'Улучшить',
    select_nft: 'Выбрать подарок',
    select_target: 'Выбрать приз',
    win_chance: 'Шанс победы',
    result_win: 'Победа!',
    result_loss: 'Неудача...',
    recharge: 'Пополнение',
    activate: 'Активировать',
    cancel: 'Отмена',
    connect_wallet: 'Кошелек',
    processing: 'Загрузка...',
    possible_drops: 'Что может выпасть',
    enter: 'Ввести',
    promo_err: 'Неверный код'
  }
};
